services:
  - type: web
    name: vpn-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    branch: main
    runtime: python
